### ISSUE TITLE
VSSpellChecker should ignore punctuation characters

### ISSUE THREAD

**Issue by Eljay-at-Work** [EWSoftware/VSSpellChecker#100]
Our comments in the code often have things like...
// set to ‘Off’

The left/right single quote are not being ignored.  They are sort-of being treated as part of the word... Off ...in the parsing.

Probably should ignore any character in the Punctuation category (Pc, Pd, Ps, Pe, Pi, Pf, and Po), as well as the 25 whitespace characters.  Or alternatively, only look at runs of characters in the Letter category (Lu, Ll, Lt, Lm, Lo).

**Comment by EWSoftware** [comment]
I can update the word splitter to handle all of the uncommon punctuation characters.  Whitespace is already handled.  It's not enough to just look for runs of letters since certain punctuation characters are handled differently based on the configuration settings, specifically '@' for e-mail addresses, periods for filename checking, underscore as a separator, and ignoring the mnemonic character.
