### ISSUE TITLE
How to disable spellchecker for selected solutions?

### ISSUE THREAD

**Issue by urza** [EWSoftware/VSSpellChecker#102]
Hi,
I need to disable SpellChecker for some solutions while keep it working on others (some projects I work on are in english - these I would like to keep SpellChecker ON, while other projects are in other languages - I would like to disable it altogether). Is this possible?

By solution I mean the Visual Studio .sln, the combination of several projects.
Thanks.

**Comment by EWSoftware** [comment]
Add a [configuration file](https://github.com/EWSoftware/VSSpellChecker/wiki/7b2bc3bb-5b5c-4d17-a88e-d58b476e49ab) for the solution and disable either or both of the "Spell check as you type" and "Solution/project" spell check options in the configuration file's [General category](https://github.com/EWSoftware/VSSpellChecker/wiki/b4a8726f-5bee-48a4-81a9-00b1be332607) settings.

If you have a mix of projects in a solution such that you want spell checking in some of the projects but not others, add a configuration file to each project in which you want it disabled rather than the solution.
