### ISSUE TITLE
Optionally spell checking types and members

### ISSUE THREAD

**Issue by wmjordan** [EWSoftware/VSSpellChecker#106]
Thank you for this great extension. It helps a lot.

Could you please add an option to also spell check the types and members?
For instance,
````C#
public class MyExtenson {
    public int VisitCountr {get;set;}
    public bool AllwaysViSible {get;set;}

    private int _Id;
    private DateTime _StartTIme;
}
````

The above code has five spelling mistakes: _Extenson_ should be _Extension_, _Countr_ should be _Counter_, _Allways_ should be _Always_ and _ViSible_ should be _Visible_, _TIme_ should be _Time_ (the underscores should be omitted).
Currently no extension could help us do these except we run the FxCop (the code analysis engine) built in VS. Is it possible to make the spell checker work with these camel-cased member names and type names?

**Comment by EWSoftware** [comment]
It's been asked for before (#15 and #64) but it's just not possible since I'd have to implement some sort of language parsing and that's really beyond the scope of anything I'd want to tackle.

As noted in one of the prior requests, code analysis does provide some support for spell checking member names.  Currently, that's the best alternative.
