### ISSUE TITLE
Cannot ignore CSS Hexadecimal colors

### ISSUE THREAD

**Issue by SirKurt** [EWSoftware/VSSpellChecker#107]
It is not uncommon to have hex codes as strings in javascript code. For example: `"#cecece"`. But the spellchecker warns me for such strings. It doesn't have a problem with strings which have number in it such as `"#ce5ece"`. I want to ignore these strings. I thought the following regex would work:
`
^((#[a-fA-F0-9]{3})|(#[a-fA-F0-9]{6})|(#[a-fA-F0-9]{8}))$`

However, I think the hash character `# `is not included in the string when matching with regex.

**Comment by EWSoftware** [comment]
As given it would always match on the three character part first leaving the rest to be spell checked.  Check for the matches from longest to shortest instead and remove the line end point anchors too since they may not always found as single lines.

`((#[a-fA-F0-9]{8})|(#[a-fA-F0-9]{6})|(#[a-fA-F0-9]{3}))`

**Comment by SirKurt** [comment]
It worked, thank you. Don't know why didn't I try it before. Sorry for any inconvenience.

**Comment by EWSoftware** [comment]
No problem.
