### ISSUE TITLE
Visual Studio 2015 Enterprise (32-bit) Freezes after extension is installed and VS restarts

### ISSUE THREAD

**Issue by astrohart** [EWSoftware/VSSpellChecker#117]
I also left this as a review for the extension.

Environment:
Microsoft Visual Studio 2015 Enterprise, latest update (32-bit version)
Windows 10 Professional x64 (latest update)
4.20-GHz, Intel(R) Core(TM) i7-7700K CPU @ 4.20 GHz
32 GB RAM

Steps to replicate:
1. Install Visual Studio 2015 Enterprise Edition and apply the latest updates and patches from Microsoft,
2. Run Visual Studio 2015 as Administrator.
3. Click the Tools menu, and then click Extensions and Updates.
4. Click the Online section in the left-hand sidebar.
5. Search for and click to Install this extension.
6. When prompted, click Restart Now.

When restarting, the Visual Studio splash screen shows.  Then, the main Visual Studio window shows and it loads the most-recently-loaded solution (per my configuration).  I also had had some code open the previous time I had Visual Studio open and the code file opened just fine.  Then, a Balloon popup showed in the tray saying, "Microsoft Visual Studio is busy waiting for an internal operation to complete."  Upon dismissing the balloon notification, then I just get a frozen, "hung" IDE.  I can click the mouse anywhere I want, but the IDE GUI/UX does not respond.  It does not complain or anything, it's just that none of the menus, toolbars, docked windows, controls, code window cursor, anything, responds when I click the mouse or type the keyboard.  Clicking on the "X" button after  After several minutes of waiting, I then force-quit Visual Studio from the Task Manager.

**Comment by astrohart** [comment]
Hi all,

Just thought I would leave a followup.  After force-quitting VS, then I simply opened the Visual Studio again. It seemed to load just fine -- second time is a charm, I suppose!

P.S. I think it would be an awesome idea to update the code to show some sort of progress bar in the UI while the extension is in the process of loading/spell checking.

Brian Hart

**Comment by EWSoftware** [comment]
You're the first to report such an issue.  I have it installed in VS2013, 2015, and 2017 without issue as do many others.  Spell checking in an open editor happens in the background so I doubt that's the issue.  Even on a very large file spell checking in the background takes only a few seconds and shouldn't impact performance in any noticeable way.

Sometimes, extensions don't install correctly from the Marketplace/Gallery.  I'd suggest removing the extension, restarting VS and making sure it's gone, then download it from here, and run the installer manually rather than using the Marketplace/Gallery.

It's also possible something else in Visual Studio is corrupted or the MEF cache is out of date.  Using Tools | Import and Export Settings | Reset all setting usually gets it back to a runnable state.

**Comment by EWSoftware** [comment]
I see you replied as I was so to follow up, as noted spell checking happens in the background so it doesn't delay editing.  Even if you're loading multiple large dictionaries startup usually happens without any noticeable delay in opening the file.  If spell checking the entire solution/project, the tool window used to do that does show a spinner.

Since it worked after a restart, VS may not have updated the MEF cache after the first restart which can cause some strange behavior.
