### ISSUE TITLE
"Add to Dictionary" does not add words to User dictionary in solution folder.

### ISSUE THREAD

**Issue by Bartolomeus-649** [EWSoftware/VSSpellChecker#122]
"Add to Dictionary" adds to private AppData dictionary, even when en-US_User.dic is added to the solution folder and "Additional Dictionary Folders" contain the relative path ".\", and the pop-up for "Alternate user dictionary" in the "Global Dictionary" group displays the full path to the solution folder where the en-US_User.dic is located.

The configuration is done as documented in the "User Dictionary" section in the "Dictionary Settings" wiki-page here on GitHub (https://github.com/EWSoftware/VSSpellChecker/wiki/af34b863-6a1c-41ed-bcf2-48a714686519)

The  en-US_User.dic is under TFS source control.

**Comment by EWSoftware** [comment]
As noted in the topic, global dictionaries are cached.  Did you close the solution and reopen it so that the changes could take effect?

**Comment by Bartolomeus-649** [comment]
Yes, even restarted VisualStudio

**Comment by EWSoftware** [comment]
Sorry for the long delay in replying.  I didn't see the notification of your last reply.  I tested this and was able to get it working as expected using the following steps:

- Open the solution in Visual Studio.
- RIght click on the solution and select the option to add a new text file or an existing dictionary file.  Rename it as necessary to *en-US_User.dic*.
- Right click on the solution node and select Add | Spell Checker Configuration file to add a configuration file at the solution level.
- In the solution configuration file, select the Dictionary Settings category.
- In the path text box, enter a single period ("." without quotes) and click Add.  Do not convert it to a relative path.  It should then appear in the list as a single period.
- Under Global Dictionaries, select the English US dictionary and click the Add button to add it to the list.
- Select the English US dictionary in the list box below the combo box and you should see the location info at the bottom change to show "Package dictionary / Alternate user dictionary".  Hovering over the "Alternate user dictionary" text should show the current solution's path.
- Save and close the solution configuration file.

You will need to close the solution and reopen it so that the changes take effect and flush any current cached copies of the global dictionary.  Once restarted, any new words added end up in the solution copy of the user dictionary file.

You mention that yours is under source control.  I suppose its possible that if you haven't got automatic checkout configured, it may be failing to check it out for some reason.  Checking it out manually should resolve any issues if that's the case.
