### ISSUE TITLE
Markdown (.md) files are not checked

### ISSUE THREAD

**Issue by taurit** [EWSoftware/VSSpellChecker#124]
Hi!

Spell checking seems to work seamlessly for plain text (.txt) or HTML (.html) files, However, I have a problem making it work for Markdown (.md) files.

![spell-check-markdown-example](https://user-images.githubusercontent.com/7702278/27352271-624e1442-5600-11e7-92f9-6094d0542b7b.png)

Is there some sort of file extension list that limits where Spell Checker can be used? Is there any workaround to make it work for Markdown format?
I wish I could use spell checking in .md files, as they usually contain lots of content that I currently copy to MS Word for proofreading :)

Thanks!
Paweł

Extension version: 2017.3.26.0
Visual studio version: 2017 Community (15.2.26430.13)

**Comment by EWSoftware** [comment]
If you have the [Markdown Editor extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor) installed, it should spell check markdown files as expected.  If not, the editor falls back to a default classifier that doesn't work as well on markdown files.

**Comment by taurit** [comment]
Thanks Eric, this partially solves the problems.
Now most content is being checked, however HTML tags inside markdown still cause come content to be skipped. HTML parser gives much better result.

I guess I'll look for some workaround to make Visual Studio treat md files the same as html files.

![spell-check-inside-html-tags](https://user-images.githubusercontent.com/7702278/27368925-92fada8a-5655-11e7-8116-de39bb698f86.png)

**Comment by EWSoftware** [comment]
Looking at the code again for another topic, the lack of support for HTML is a limitation.  It currently skips anything reported by the classifier as HTML since it just presents it as one block of text with no distinction as to the actual content.  Figuring out what's actual content as opposed to HTML elements and attributes would require further parsing of the given block of text.  I may go back to it at some point to extend it but for now it just skips such blocks.
