### ISSUE TITLE
Options unusable in dark theme

### ISSUE THREAD

**Issue by cyotek** [EWSoftware/VSSpellChecker#13]
Hello,

I've just upgraded to latest version but when I go into the options page it's pretty unusable. I use the "Dark" VS theme and the VSSpellChecker uses the dark background, but also keeps black text for all labels and frames, making the whole thing unreadable. Changing the scheme to Light fixes this.

Would be nice if the text colors followed the VS scheme.

Thanks;
Richard Moss

PS: On a related note, I have also configured the font to be slightly larger. When I switched themes from dark to light so I could read the options, I noticed that the text size suddenly became smaller. This is fine, what I did note is that the button sizes didn't change. I suspect if people are using text sizes even larger than normal (my IDE font is set to 14pt), then the text in the buttons possibly won't appear properly (other buttons in the IDE, for example those in the VS options dialog scale upwards with the font size). A minor issue compared to the text color for sure!

**Comment by EWSoftware** [comment]
I've fixed the theme and font size issues but I'm going to wait a few days and see if any other issues are reported.  I'll probably publish an update this weekend to fix this and any other issues.  Regarding the theme, the colors used are the same used for the light and blue themes so it won't blend but it will be usable.  I'll consider actual theme support once I drop support for VS 2010 since it doesn't do things the same way and I can't be bothered to code in workarounds just to support the dark theme right now.

**Comment by cyotek** [comment]
Cool, thanks for the prompt reply! Look forward to the update.
