### ISSUE TITLE
Incorrectly handles words with double quotes between words

### ISSUE THREAD

**Issue by ILD3225** [EWSoftware/VSSpellChecker#133]
Incorrectly handles words with double quotes between words
![1](https://user-images.githubusercontent.com/14194323/29911822-75ea7482-8e40-11e7-9032-75de6534450f.png)

**Comment by EWSoftware** [comment]
In this particular example, that is by design and occurs when it looks like two strings are being concatenated.  Join the two strings together and you'd get "test wordanother test word".  "wordanother" isn't valid so it flags it.  This change was made in the latest release to stop it flagging valid words that get split across strings in designer code which happens a lot.  It'll still flag split words that are genuinely misspelled or appear to be as in this case due to a missing space.  Granted, this case is in a comment and it could ignore it but it may not always pick up on the proper context.

However, I do see that if the "+" is removed, it still flags it so the check does need to be extended to ensure that at least a concatenation operator is present in the intervening whitespace between string literals.
