### ISSUE TITLE
Support for HTML fields of work items

### ISSUE THREAD

**Issue by WhackedRak** [EWSoftware/VSSpellChecker#137]
Thanks for updating and maintaining this tool!
I've looked around but haven't found anything that could enable spell check in HTML fields of work items. Is it possible this tool could ever support that feature?   This would be great as I know a lot of test teams that write and edit bugs in these TFS fields.  Are there any alternatives and what would it take to implement this?

Thanks again

**Comment by EWSoftware** [comment]
Unfortunately, that isn't possible as far as I know.  Spell checking in WPF text boxes works because I can register an event handler with the static event manager in WPF.  Spell checking HTML would probably require some sort of JavaScript interface and adorner which doesn't exist within the package either.

**Comment by WhackedRak** [comment]
I thought as much.  I may have to look into one such adorner solution soon or a TFS entry tool outside VS.
Thanks for your answer.
