### ISSUE TITLE
Menu isn't visible in Tools -> Menu

### ISSUE THREAD

**Issue by fwd079** [EWSoftware/VSSpellChecker#144]
Hi,
May be I am being thick here, but this extension is installed and works fine, however, I wanted to add British English so I googled the help and it says I could see the Spell check in Tools menu, but somehow it is not showing, tried restarting Windows but to no avail. (Win 7 64 bit Enterprise). 
Please help.
Regards

.
![image](https://user-images.githubusercontent.com/7912632/32842566-4c4f6658-ca15-11e7-8d68-57e7b866e586.png)

**Comment by EWSoftware** [comment]
Go to Tools | Extensions and Updates, select the Installed category and look for "Visual Studio Spell Checker (VS2017 or Later)" and that it's the latest release (v2017.8.26.1).  If it's there, it's installed.  Select it and make sure it's enabled.  If not, a button will show up letting you enable it.  You can also try uninstalling it, and reinstalling it.

**Comment by fwd079** [comment]
Hi, thanks for tips, didn't work unfortunately.
I have looked, it was Enabled and then I tried uninstalling and reinstalling it. But didn't work, however I noticed the digital signature information is missing? Could that be the reason VS is allowing it to _work_ but not _showing_ it in menu?
Regards

![image](https://user-images.githubusercontent.com/7912632/32847229-54281436-ca21-11e7-8d34-2b3cd708fa9a.png)

**Comment by EWSoftware** [comment]
The extension isn't signed so that's normal.  It should work either way.  Are you current on Visual Studio updates?  Visual Studio 15.3 or later should work.  Some stuff got moved around in the Visual Studio assemblies in 15.3 so anything prior to that may have issues.

As a last resort, you could use Tools | Import and Export Settings and use the Reset all settings option.  That should put Visual Studio back into a default state and fix up any issues with the MEF cache and other extension related stuff.

**Comment by fwd079** [comment]
Thank you, unfortunately tried all that, I am on VS 2017 15.4 Professional by the way, the reset all didn't solve it, uninstalling then  resetting, then starting VS as admin and resetting all settings, restarting VS as admin and tried installing. It installs fine, works too, just doesn't show any menu items.

I don't want it to break, or VS for that matter, since it is working and just not showing menu, I am just about to give up.

Is there any hotkey to show pop-up settings instead of Tools -> Menu so that I can use it instead please?

Regards
.
![image](https://user-images.githubusercontent.com/7912632/32882151-50dff37c-caab-11e7-815d-3447676dde92.png)

**Comment by EWSoftware** [comment]
I don't know why the menu items won't show up.  You should be able to bind keys to the commands though.  Go to Tools | Options and select the Environment | Keyboard category.  In the search text box, type in "spell" and you should see the speller commands:

![image](https://user-images.githubusercontent.com/10552523/32900754-0f2c97bc-caa3-11e7-8dbe-5416acfe9628.png)

For the global configuration editor, search for "global" and you should see Tools.EditGlobalConfiguration.  That's the one that edits the global spell checker configuration file.

**Comment by fwd079** [comment]
Thank you for reply, Spell brings up nothing, I then tried File.s and it didn't bring up anything relating to Spell. Well so I guess something is amiss in my VS 2017 15.4 Professional itself, I am thinking it might be something to do with rights or something from IT Dept.

Anyway, since I cannot get it to show menus etc. and it is not showing me those options **but** the checker it self works fine and fixes my mistakes, I'll leave it here. Thank you for your help so far, appreciated. Now you can either leave it open for your records / bug log etc or close it as cannot reproduce flag etc.

Regards
.
![image](https://user-images.githubusercontent.com/7912632/32943466-1e60c28a-cb84-11e7-8505-12c5e0c10e70.png)

**Comment by EWSoftware** [comment]
Since the items aren't showing up in the commands or menus it either isn't registering correctly or isn't loading the package for some reason.  The editor spell checking parts are MEF-based and are loaded independently of the other parts.  Unfortunately, since it's not something I can reproduce I don't know why it may be failing to load the package in this particular case.
