### ISSUE TITLE
HTML Code editing: ignore program commands

### ISSUE THREAD

**Issue by ggmggm** [EWSoftware/VSSpellChecker#148]
HTML Code editing with Visual Studio and Spell Checker: 
  I can not find a solution that program commands will be ignored in the head region:
php
json
Arial
{ #fdfdfd  (names of variables)

![image](https://user-images.githubusercontent.com/34009357/34324647-b019323a-e87a-11e7-85bd-7be987c48292.png)

**Comment by EWSoftware** [comment]
Can you send me a small example project?  It looks like most of the items are syntax highlighted so I'll see if the classifier is returning anything specific that can be ignored for those elements.

Worst case, you can use the [exclusion expressions](https://github.com/EWSoftware/VSSpellChecker/wiki/6216eedb-6434-4cad-be06-576814e0b735) option in the spell checker configuration to exclude text using regular expression matches.

**Comment by ggmggm** [comment]
Hello!

The failure is on all my *.htm/*.html
Perhaps something wrong with my settings?
Please see the the attachement.

Two of my files (thousands with the same failures) also as attachements.

I hope you can find something.

Merry Christmas

GM

Hint: It is not possible to attach html or VSSpellChecker.vsspell
So I send the E-Mail to notifications@github.com
[EWSoftware/VSSpellChecker] HTML Code editing: ignore program commands (#148)

**Comment by ggmggm** [comment]
Hello!

I change the extension of htm to txt, so that I can upload it:
[S8183H1.txt](https://github.com/EWSoftware/VSSpellChecker/files/1586707/S8183H1.txt)
[2010-04-07_de-beers-millennium-blue-diamond-sale-sotheby.txt](https://github.com/EWSoftware/VSSpellChecker/files/1586708/2010-04-07_de-beers-millennium-blue-diamond-sale-sotheby.txt)


I change the extension of vsspell to txt, so that I can upload it:
[VSSpellChecker.txt](https://github.com/EWSoftware/VSSpellChecker/files/1586709/VSSpellChecker.txt)


GM

**Comment by EWSoftware** [comment]
This is a problem caused by the way the editor works.  With HTML files, the CSS and script blocks are separate buffers.  The problem with those secondary buffers is that there isn't a way to obtain information about the file they are contained in so they are ignored.  Even if they weren't ignored, the overall HTML tagger would still return those sections as plain text which is what is happening now.

As noted above, I think your only option here is to use exclusion expressions to ignore the unwanted spans.
