### ISSUE TITLE
No smart tag menu in string literals

### ISSUE THREAD

**Issue by sensboston** [EWSoftware/VSSpellChecker#157]
Smart tag menu (very useful feature!) is appearing on comments but not on strings in C# code (btw, Ctrl+. is working). Could you please fix? Thank you!

![correct](https://user-images.githubusercontent.com/1036158/39198468-2fe72d20-47b5-11e8-9a4e-49eed38b973f.png)
![incorrect](https://user-images.githubusercontent.com/1036158/39198478-32377864-47b5-11e8-8452-f9cfe0827319.png)

**Comment by sensboston** [comment]
I confirm, MS fixed their bug (not yours) :) You may close issue now, but **THANKS** for the prompt response!

**Comment by marinoscn** [comment]
I have the latest release of Visual Studio 2017 (15.7.3) and this issue is still not fixed.

I do not get any smart tags for misspelt words in string literals:

![image](https://user-images.githubusercontent.com/38280851/40825326-ea1d9e44-657f-11e8-8aff-1fe40a56c624.png)

![image](https://user-images.githubusercontent.com/38280851/40825377-07896b84-6580-11e8-9ef2-105f55d1478b.png)

Please re-open this issue.

**Comment by marinoscn** [comment]
Please ignore my last post.

I now know what is going on.  It is  ReSharper  that is interfering with the smart tag.
