### ISSUE TITLE
Disable en-US

### ISSUE THREAD

**Issue by sergedornseiffer** [EWSoftware/VSSpellChecker#159]
I would like only use the en-GB dictionary. Is there way to disable the en-US.

**Comment by EWSoftware** [comment]
Set the language to use in the [Dictionary Settings](http://ewsoftware.github.io/VSSpellChecker/html/af34b863-6a1c-41ed-bcf2-48a714686519.htm#Languages) category of the configuration file.  If you only select one language, that will be the only one used for spell checking.

You can set it in the global configuration so that it applies to everything or any solution/project/folder/file configuration to limit it to the related set of files.

**Comment by sergedornseiffer** [comment]
Thank you very much. That helpes
