### ISSUE TITLE
Keep getting "No text editor is selected.. currently disabled, or .."

### ISSUE THREAD

**Issue by JamesWHurst** [EWSoftware/VSSpellChecker#16]
Hello,  when I invoke "Spell Check Active Document", sometimes - I get the dialog saying "No text editor is selected, the spell checker is currently disabled, or the file is excluded by filename extension."

It worked a couple of times before, and I *do* have a codefile.cs file open in Visual Studio, and I put focus on it. Cannot this at least tell me *which* of those issues is actually the problem?!

How do I get this to work?

Thanks,  jh.

**Comment by EWSoftware** [comment]
Which version of Visual Studio are you using?  Are you using the latest release (v2015.2.21.0)?

If a text editor has the focus and the cursor is in it, that eliminates the first possible cause.  Select **Tools | Spell Checker | Edit Global Configuration** and select the **General Settings** category.  The "Spell check as you type" option should be set to Yes.  Select the **Excluded Filename Extensions** category and see if the ".cs" extension is there.  You can clear the list to enable spell checking for all extensions.  You can also click the **Reset** button in the lower left of the editor window and, when prompted, click Yes to reset the entire configuration to its default state.

Save the configuration file, close the affected editor, and re-open it so that the configuration changes can take effect.  If enabled, the spell checker tool window should pick it up.  Also, if you type a misspelled word in the editor, you should see the squiggle underline indicating the spelling error.

Note also in this latest release that there are solution, project, folder, and file-specific [configuration files](https://github.com/EWSoftware/VSSpellChecker/wiki/Configuration-Files).  See the linked topic for details.  If you've added any one of those to your solution or project and inadvertently disabled spell checking that would also affect it.  You can edit those as above or just delete them to remove their effect.  As above, close and re-open the editor to have the new settings take effect.

**Comment by JamesWHurst** [comment]
Hello - thank you for responding.

I'm using VS 2013  Ultimate Update 4, on Windows 8.1 x64.

I tried it with "Spell check as you type" set to yes - still doesn't work. Although what I really want to do, is bring up existing C# files to spell-check.

There are no Excluded Filename Extensions.

I tried the Reset button.

Q: How do you save your settings - am I correct in assuming it's by selecting Visual Studio's "save" command as is normal for any editor window?

Still having this problem!  I open a C# file (extension .cs), place my mouse-cursor within it, and then in the VS menu-bar I select Tools > Spell Checker > Spellcheck Current Document.

**Comment by EWSoftware** [comment]
In the latest release, the configurations are opened in an editor so File | Save or saving when prompted when closing if you made changes will save the changes.   If you type a misspelled word in the editor, you should see the squiggle underline indicating the spelling error.  Is that even happening?

**Comment by JamesWHurst** [comment]
Yes - I did at one point see the squiggle underline, which I assumed was your spellchecker. But I can't get it to spell-check a file, which is what would be useful to me.

**Comment by EWSoftware** [comment]
My point is, do you see the misspelling underlines now?  If not, then it isn't even spell checking as you type.  If you had an older version installed and this started after the last update.  Try removing the extension using the extension manager, restart Visual Studio, and then install it again.  A couple of people have had an issue where the automatic update didn't work correctly in the past and a reinstall corrected the problems they were having.

**Comment by JamesWHurst** [comment]
Ok - that apparently solved my issue. Thank you very much!

I re-installed, re-enabled it, and now it works just fine.

PS: It would be nice if it un-collapsed the Visual Studio regions, so we could see where it is pointing to when it spots a mis-spelling. Very minor.

This is being very useful now!

**Comment by EWSoftware** [comment]
I tried looking for a way to expand the regions a while ago but came up empty.  I'll have another look and see if I can find a way.  If so, I'll implement it.

**Comment by EWSoftware** [comment]
My search skills were apparently better today and I have found a way to expand the collapsed regions.  I'll be issuing an update later today that contains this change plus a couple of other fixes and features.
