### ISSUE TITLE
Ignore once not compatible with Spell Check Solution/Project

### ISSUE THREAD

**Issue by sergedornseiffer** [EWSoftware/VSSpellChecker#161]
Before continuing. Brilliant Tool. Thank you very much.

My issue is the following. I have marked a comment as "Ignore once", and indeed it does not show up on my code window anymore. Perfect, just what I want. If I go to Tools / Spell Checker / Spell Check Entire Solution a Windows shows up on which I have the list of issues after having pushed the Start button. Unfortunately, the one that I marked as "Ignore once" is displayed in the list.

Thank you very much

**Comment by EWSoftware** [comment]
Words ignored once in the editor windows are local to the related editor windows.  Likewise, words ignored once from the solution/project spell check tool window are local to the tool window.  I'll have to see if it's possible to get at the text view properties so that I can access the related tagger to get the list of ignored words in the editor.  It does look for open editors for the file to get the current content when spell checking so it may be possible to do that and filter them out.
