### ISSUE TITLE
Standard words not in dictionary

### ISSUE THREAD

**Issue by xiecsuk** [EWSoftware/VSSpellChecker#17]
I have just started to use Visual Studio Community 2013 which includes this spellchecker as a standard component. I would therefore expect common words such as charset, viewport, favicon, config, and many more, to already be in the dictionary. Or am I missing something here. Is there something I should do that I haven't done.

**Comment by EWSoftware** [comment]
It's news to me that my extension is included by default with the community edition.  More likely than not it got pulled in from the settings of another version of Visual Studio that you perhaps had installed earlier.  Anyway, with regard to the default dictionary, it's a standard Open Office US English dictionary.  As such, it may not contain what we consider common programming terms.  You can add them to the user dictionary using the smart tag option or the spell checker tool window so that they aren't flagged as misspellings and are offered as corrections for other misspellings when appropriate.

**Comment by xiecsuk** [comment]
It must have been part of the NuGet packages when I installed the Community edition because I didn’t install it. I didn’t have any other versions if VS installed. I had completely cleaned my system before installing.

I didn’t realise it was just a standard dictionary. I assumed it was set up as a development dictionary. Sorry about that. 

As this is my first website using this checker, I will build up the dictionary as I progress through the generated code.
