### ISSUE TITLE
Could not find 'Microsoft.VisualStudio.Threading' (#156)

### ISSUE THREAD

**Issue by Michal-MK** [EWSoftware/VSSpellChecker#174]
The same error as in #156 
With Visual Studio Comunity Edition 15.7.6.
Spell Checker v2018.8.25.0

Current document works, anything bigger displays the same image as in the mentioned issue. 

Tried with other extensions disabled and reinstalling.

**Comment by EWSoftware** [comment]
Have you tried updating to the latest release?

**Comment by Michal-MK** [comment]
Will do. I'll report back once it is done downloading.

**Comment by Neone-pl** [comment]
Had same issue on VS 15.7.4 

Updated to 15.8.2 and now it works fine.

**Comment by EWSoftware** [comment]
I'm updating the extension to support asynchronous package loading which will be required soon.  As part of that, I'm updating the project to use the NuGet packages for the Visual Studio assemblies rather than the ones installed with the SDK which seem to be causing this issue when new updates are issued.  Staying back a couple of point releases with the NuGet packages should alleviate this problem.
