### ISSUE TITLE
Consider adding "Region Ignore Spelling Directive"

### ISSUE THREAD

**Issue by LukeOwlclaw** [EWSoftware/VSSpellChecker#180]
In code we often have blocks with many unwanted spelling errors, e.g. test data which contains errors on purpose,  the definition of all time zones, 

For these regions an Ignore Spelling Directive would be useful, e.g. 

    // Region ignore spelling
    switch (time)
            {
                ...
                case "Fiji Standard Time": return "(UTC+12:00) Fiji";
                case "Magadan Standard Time": return "(UTC+12:00) Magadan";
                case "Kamchatka Standard Time": return "(UTC+12:00) Petropavlovsk-Kamchatsky - Old";
                case "Tonga Standard Time": return "(UTC+13:00) Nuku'alofa";
                case "Samoa Standard Time": return "(UTC+13:00) Samoa";
            }
    // Endregion ignore spelling

**Comment by EWSoftware** [comment]
You can use the [Ignore Spelling directive](http://ewsoftware.github.io/VSSpellChecker/html/3094ee74-88ae-4355-b702-23dcd55b4197.htm).  It doesn't do it by region but will ignore words within the file without having to add them to a configuration file.

Regions could be supported for solution/project spell checking but implementing them in the tagger for the editors is rather difficult if not impossible due to the way the classification spans are handled.
