### ISSUE TITLE
Please add "add to custom dictionary" context menu item

### ISSUE THREAD

**Issue by WaldemarH** [EWSoftware/VSSpellChecker#198]
Hi guys

I've tried the extension and it works really good. :)

Now there were two thing that I was missing from the first second I was using it:

1. context menu item "Add word to custom dictionary"

Now I've tried to load the dictionary (user.txt) in the options, but the file was just read and that was it. So every time I added a word I had to reload it, which is simply said very annoying.
So if you could add an option to track user dictionary file it would be a good first step.
Now the better one would be to have an option to setup user dictionary file that would be automatically updated if you would select the word and click the "Add to custom dictionary" context menu item.

2. to have a per solution or per project dictionary.

So if the 1. point would be upgraded to have an automatic solution/project user dictionary it would also be a cool thing, as some kind of words only happen in specific projects (normally hardware related). And that dictionary would be located in the solution/project directory so that it would be stored into git.
   
So if you could add the context menu:
- Spell checker
   - Add to solution/project dictionary
   - Add to user dictionary

Anyway thanks again for awesome extension.

Best regards
Waldemar

**Comment by EWSoftware** [comment]
User dictionaries for each language are supported and when you use the *Add to Dictionary* option it adds the word to that file.  The user dictionary files must be named after the language (*en-US_User.dic* for example).  If you import a file into it, it just adds the words from the source file at that time.  If you open the spell checker's configuration and go to the *Dictionary Settings* category, you'll see two labels at the bottom right of the page.  If you hover over the user dictionary label with the mouse, it will show the location of the user dictionary file that it is using.

![image](https://user-images.githubusercontent.com/10552523/60619087-b5a54400-9d8c-11e9-9ead-8f9aad7efdd6.png)

By default, they are stored in the Application Data folder.  If you want to move the user dictionary to a location that you control so that the file is backed up for example, you can add the folder to the *Additional Dictionary Folders* list and move the user dictionary to that location.  For example, some people add the My Documents or their One Drive folder to the list and move the user dictionary there.  See the [User Dictionary section](http://ewsoftware.github.io/VSSpellChecker/html/af34b863-6a1c-41ed-bcf2-48a714686519.htm#UserDictionary) of the related settings topic for more information.

As noted in the help topic, if you add a solution or project configuration file and add an additional path
that is relative (.\\ for example), it will look in the same location as the solution/project configuration for the user dictionary.  Any words added would get added to that user dictionary instead.  However, as currently implemented, the solution/project user dictionary overrides those at higher levels so it's not a merger of all of the user dictionaries, just that one.

Typically, you don't want words at the solution or project level offered as spelling suggestions like words in the user dictionary.  As such, adding them to the [Ignored Words](http://ewsoftware.github.io/VSSpellChecker/html/c592c4d8-7387-47fe-9b79-28bf0168f447.htm) category of the solution or project configuration file prevents them from being marked as incorrect spellings.

Another option if you don't want the bother of maintaining a list in the configuration file is to use the [Ignore Spelling directive](http://ewsoftware.github.io/VSSpellChecker/html/3094ee74-88ae-4355-b702-23dcd55b4197.htm) within the source code file itself.

Try those options out.  If you do need the solution/project words offered as corrections rather than just being ignored, let me know and I'll investigate adding support for multiple user dictionaries.
