### ISSUE TITLE
Dark Themed Windows

### ISSUE THREAD

**Issue by TheWhiteWolves** [EWSoftware/VSSpellChecker#20]
It would be good if you could change the colouring of the Tool Window (the Spell Check Active Document window) and the settings window to follow the same colourings of the dark theme if that is what you have selected (like myself and many people do).

I currently have the Spell Check window docked with my properties window and it would be good for it to be the right colour when I switch to it.

**Comment by EWSoftware** [comment]
This is something I'll consider when I no longer provide support for VS 2010 which doesn't contain the same theming support.

**Comment by JoeEarly** [comment]
Any plans for this wee Enhancement since 2015 is now out

**Comment by EWSoftware** [comment]
I've dropped support for VS2010/2012 for the next release.  I'm wrapping up a few changes for the next release but this won't make it into it.  I'll consider it for the next one.

**Comment by JoeEarly** [comment]
Nice, cheers for the reply :)

**Comment by TheWhiteWolves** [comment]
Nice work, do you have an ETA on the next release or have you still got alot of work to sort out for it?

**Comment by EWSoftware** [comment]
I issued a release just last week so I wasn't planning on issuing another for a while.  Figuring out and getting the theme stuff to work came together a lot quicker than I thought it would.  The changes are purely visual and the only other change was to alter how suggestions for multiple languages are presented so I plan on waiting until I get the full solution/project spell checking implemented so that it's more worthwhile.  I've begun work on that but don't have a good idea of when it will be finished.

Oddly, to me anyway, I had more requests for theme support than I did for the solution/project spell checking which ran a close second.  I've always used dark colors for the editor but wasn't too keen on the overall dark theme.  After using it for testing this change, it's grown on me and I may start using it :smile:.

**Comment by TheWhiteWolves** [comment]
kl np, just wanted to get an idea of it was going to be soon so I would know when to look at the extension manager to update my work computer.

And you should use the dark theme, personally its a lot better on the eyes when you have to stare at the screen all day.

**Comment by JoeEarly** [comment]
Top job Eric,

I did see the CR go in and was going to download but am happy to wait until
your ready.

On Mon, Aug 24, 2015 at 5:34 PM, TheWhiteWolves <notifications@github.com>
wrote:

> kl np, just wanted to get an idea of it was going to be soon so I would
> know when to look at the extension manager to update my work computer.
>
> And you should use the dark theme, personally its a lot better on the eyes
> when you have to stare at the screen all day.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EWSoftware/VSSpellChecker/issues/20#issuecomment-134291975>
> .
>



-- 
Joey

**Comment by TheWhiteWolves** [comment]
just wanted to say thanks for the dark themed window, my eyes feel alot better now and overall the latest update itself looks really good, thanks for the great work.
