### ISSUE TITLE
Highlight in literals doesn't work

### ISSUE THREAD

**Issue by avs87** [EWSoftware/VSSpellChecker#203]
Highlight in literals works only if we have comment above misspelling literal.  If we have not, highlight shows only for a few seconds.
![2019-10-02_09-19-35](https://user-images.githubusercontent.com/56062954/66022867-f29de580-e4f7-11e9-8c7a-fc5faeab8df0.gif)
My configuration is:
  - Microsoft Visual Studio Community 2017 Version 15.9.16
  - Visual Studio Spell Checker Version 2019.7.8.0

**Comment by EWSoftware** [comment]
The common tagger is not handling the preprocessor keywords properly.  It'll be fixed in the next release.  In the meantime, a workaround is to go into the configuration, select the [C# Options category](http://ewsoftware.github.io/VSSpellChecker/html/09cc5bfa-9eba-47e5-ba5f-a36e04f09b0d.htm) and set the "Apply the above options to all C-style languages as applicable" option to Yes.  This enables the C# tagger for all C-style languages and it handles the preprocessor keywords properly.

**Comment by avs87** [comment]
Thanks! It works fine now. :thumbsup:
