### ISSUE TITLE
How to exclude commented-out code

### ISSUE THREAD

**Issue by franzalex** [EWSoftware/VSSpellChecker#221]
Usually, I comment out code using the double comment mark in C# (```////```). When I do this, variable names (which are often contractions) tend to be highlighted as misspelt words.

The extension failed, however, to ignore commented-out code using the following exclusion regular expression:

```
(\/){4}([^\/]*)
```

How do I achieve my intended purpose of ignoring code commented out using the double comment mark?
Thanks.

**Comment by EWSoftware** [comment]
The comment delimiters are not included in the spell checked text so are not present for the expression to find.  Go to the [C# Options](http://ewsoftware.github.io/VSSpellChecker/html/09cc5bfa-9eba-47e5-ba5f-a36e04f09b0d.htm) in the configuration and enable the option to ignore quadruple slash comments.

**Comment by franzalex** [comment]
Thanks for the response, @EWSoftware. Is there any chance that such an option exists for VB?

**Comment by EWSoftware** [comment]
In the editor, all other languages use a generic tagger that uses the code classifications from the editor so it doesn't support the same options.  That's not to say it can't be done but would require creating custom taggers and option sets for each requested language.  

It can be implemented fairly easily for the project/solution spell checker as it uses a configuration file to define how the text is classified and you can [override existing definitions or add new ones](http://ewsoftware.github.io/VSSpellChecker/html/0ff35371-69b5-48dd-a062-037abe2469de.htm).  For example, you could clone the rules for the [VBStyle](https://github.com/EWSoftware/VSSpellChecker/blob/master/Source/VSSpellChecker/Classifications.config#L43) classifier and add a rule to match `''''` comments and classify them as undefined so that they are ignored for project/solution spell checking.
