### ISSUE TITLE
CSHTML files not being fully spellchecked.

### ISSUE THREAD

**Issue by hjgermain** [EWSoftware/VSSpellChecker#251]
the following code is from a cshtml file. The C# @{} "code" is checked and "mispelled" is found. The rest of the file (e.g., notfound) is not seen as incorrect.

```
<body>

    notfound

    @{
        // mispelled 
    }

</body>
```

**Comment by EWSoftware** [comment]
Many of these are dependent on the project type and how the editor interacts with them.  Can you provide a small example project that demonstrates the issue?

**Comment by hjgermain** [comment]
Visual Studio 2022
Visual Studio Spell Checker 2022+
[WebApplication3.zip](https://github.com/EWSoftware/VSSpellChecker/files/7689088/WebApplication3.zip)
 extension
Create new project
asp.net core web app MVC
take a look at Views/Home/Index.cshtml

**Comment by EWSoftware** [comment]
I had to associate the HTML tagger with the Razor content type so that it handles the inner text elements.  It'll be fixed in the next release due out soon.  That said, the classifier for the Razor content type works oddly in VS 2022.  It appears to classify the text out of sequence.  As such, you will likely see it spell check attribute values that it previously ignored even though they're not in the list of included attributes to spell check.  Unfortunately, that isn't something I have control over.
