### ISSUE TITLE
[Feature] Add misspelled word to solution dictionary 

### ISSUE THREAD

**Issue by DamianSuess** [EWSoftware/VSSpellChecker#253]
As a user, I would like the ability to add misspelled word to the ignore list for my solution via the code editor. Currently, it only adds to the global `xx-YY.dic` file found in the `%LOCALAPPDATA%\EWSoftware\Visual Studio Spell Checker\xx-YY.dic` file rather than providing the option for the solution's `*.vsspell` file.

This would be greatly appreciated so that I don't have to manually find the `.dic` file and copy them over into the XML.

Thank you!  btw, love the extension.

**Comment by EWSoftware** [comment]
That can be done if you use an ignored words list file rather than putting the words in the configuration's ignored word list.  In the same category at the bottom, you'll see a textbox for specifying the ignored words list file to associate with that configuration.  The file can be set in the global configuration or any other file-related configuration.   Once set, reload any open editor files, select a misspelled word, and you'll see an option in the context menu at the bottom "Add to Ignored Words File".  The submenu will list the ignored words files it can be added to.

**Comment by DamianSuess** [comment]
Thank you for pointing that out! Great tip. Hope you have a wonderful weekend
