### ISSUE TITLE
Spell Check Current Document Failure

### ISSUE THREAD

**Issue by PaltryProgrammer** [EWSoftware/VSSpellChecker#261]
Greetings Kind Regards Thank You for providing VSSpellChecker Upon selecting "Spell Check Current Document" the results window states as shown in attached PNG file. I do not know how to "Select a text editor" Kindly Advise Please note it is not disabled and no files are excluded by extension - Thank You Kindly

![VSSpellChecker results window](https://user-images.githubusercontent.com/48535920/185906532-1e9e2b0f-2f00-4ef3-8e14-8bf3c0431724.png)

**Comment by EWSoftware** [comment]
"Select a text editor" just means make sure an editor window is active before you invoke the option to spell check the current document.  If you have an active editor and you haven't disabled Spell Check as You Type in the options, try removing the extension using the extension manager, restart Visual Studio, and then install it again. Some people have had an issue where it didn't work correctly and a reinstall corrected the problems they were having.  Others have been able to get it working by downloading it from the [Releases Page](https://github.com/EWSoftware/VSSpellChecker/releases) rather than installing from the marketplace.

Another was able to get it to work if they ran Visual Studio as an administrator so it appeared to something related to their permissions. You can probably install the package as an administrator and install it for all users. Download it from the Releases Page or the Marketplace and then run VSIXInstaller.exe with the /admin command line option. That should install it for all users, admin or not. You can find the tool in %ProgramFiles%\Microsoft Visual Studio\2022\Community\Common7\IDE (adjust the path for your edition). If that works, the only thing to be aware of is that extensions installed for all users don't auto-update so you need to install any future updates manually the same way.
