### ISSUE TITLE
Would be nice if there was a way to ignore comments that start with //

### ISSUE THREAD

**Issue by i00** [EWSoftware/VSSpellChecker#267]
There is currently an option:
"Ignore quadruple slash single line comments (////)"

... it would be good if this applied to ANY comment - so that if the comment started with // it would be ignored... 
So in C# //// would be ignored
.. in python #// would be ignored
.. in SQL --// would be ignored
.. in VB '// would be ignored
.. etc

**Comment by EWSoftware** [comment]
There is already an option to ignore standard double-slash comments under the same [C# options](http://ewsoftware.github.io/VSSpellChecker/html/09cc5bfa-9eba-47e5-ba5f-a36e04f09b0d.htm).  It cannot be applied to the other languages as it just isn't possible to handle all languages individually.  You may be able to achieve the desired result using [exclusion expressions](http://ewsoftware.github.io/VSSpellChecker/html/6216eedb-6434-4cad-be06-576814e0b735.htm) for the other languages (`//.*?$` for example since the slashes would be included as part of the comment text in other languages).
