### ISSUE TITLE
Clashes with GhostDoc auto documentation functionality

### ISSUE THREAD

**Issue by Dany-HBK** [EWSoftware/VSSpellChecker#271]
Just installed this very helpful extension.
I'm also using the _GhostDoc_ extension, which automatically fills the inline documentation fields when typing in `///` in front of a function the first time (C#).
Now with _VSSpellChecker_ active, this feature is blocked and I get only the default behavior of _Visual Studio_ (empty fields). Deactivating _VSSpellChecker_ brings back _GhostDoc_'s auto-fill.
Now I'd like to use both extensions, please ;)
Thanks, Dany

**Comment by EWSoftware** [comment]
I installed the community version of GhostDoc and had no issues and GhostDoc worked as expected.  I suppose you could try uninstalling and reinstalling both extensions to see if that corrects the issue.  If the problem persists, I suggest reporting the issue to SubMain and to see if the issue is with GhostDoc.  The problem here is that GhostDoc is closed source so I can't see what it's doing and cannot diagnose any issues with it or see how it interacts with my extension.  If SubMain determines that the issue is with my extension and can tell me what is wrong, I can likely fix it then.
