### ISSUE TITLE
A way to turn off VSSpell001 globally

### ISSUE THREAD

**Issue by hrumhurum** [EWSoftware/VSSpellChecker#279]
VSSpell001 goes in the way and pollutes the projects with correction suggestions like: `Correct spelling of Xna`.

The problem is that checks of programming language identifiers will never work because the boundaries of the field are limitless: there are tons of industries with their own acronyms, jargons and vocabularies. So VSSpellCheck should not try to impose the invasive corrections on those. And no vocabulary changes can fix that - there is just too much variety in programming to ever have a common vocabulary of identifiers.

I know that a diagnostic like VSSpell001 can be disabled but there is no way to do it on the global (=user) level. It is too much work to configure each and every solution for something I was never asking for.

Also I understand, that VSSpellCheck requires constant maintenance (thank you for that!) and now there are those pesky users like me with their problems. But, once again, the recent VSSpellCheck update is a bit ruthless. This situation kind of reminds me of GhostDoc - once a helpful tool that was later acquired and gradually became super counterproductive by imposing its selfish wits on everybody.

**Comment by EWSoftware** [comment]
It wasn't my intention to force it on anyone so it can be disabled at the global level.  If you'd prefer to turn off the code analyzer completely, it can be done in the [General settings](https://ewsoftware.github.io/VSSpellChecker/html/b4a8726f-5bee-48a4-81a9-00b1be332607.htm) by setting the "Enable spell checking code analyzer in supported languages" option to No.  Do that in the global configuration and it will then effectively work as the prior versions have (strings, comments, and plain text only).

If enabled, there are [several options](https://ewsoftware.github.io/VSSpellChecker/html/09cc5bfa-9eba-47e5-ba5f-a36e04f09b0d.htm) to control what is spell checked for identifiers mainly related to visibility.  I use them since I don't care about the private/internal members so much, just the public API.  There is also the option to define [ignored words and keywords](https://ewsoftware.github.io/VSSpellChecker/html/c592c4d8-7387-47fe-9b79-28bf0168f447.htm).  The default configuration contains several sets but can't possibly define them all so they will need updating based on your own circumstances.  Though perhaps not as prevalent, this issue has always existed even for text in strings and comments.  Likewise, the dictionaries don't contain all known words and their variations so there's always a need to add words to the user dictionary.

**Comment by hrumhurum** [comment]
> it can be done in the [General settings](https://ewsoftware.github.io/VSSpellChecker/html/b4a8726f-5bee-48a4-81a9-00b1be332607.htm) by setting the "Enable spell checking code analyzer in supported languages"

Thank you.

However, the documentation says nothing about how to access those general settings. So it kind of keeps a user wondering where those general settings are? It would be super helpful to see that information in the documentation. 

Another approach is to add the configuration tab to Tools -> Options... dialog of Visual Studio, so that people could tune VSSpellChecker to their preference.

**Comment by EWSoftware** [comment]
It is referenced in the [Installation Instructions and Usage Notes](https://ewsoftware.github.io/VSSpellChecker/html/e339cac1-9783-4c2a-919f-88436c78fef8.htm)

**Comment by hrumhurum** [comment]
While the documentation indeed has the information, the problem is that the relevant information is n-clicks away from the place where it is expected to be seen. If we talk about "General settings" then it's always a good idea to provide the information about changing them, right there and not n-clicks away.

I was lucky to find the info just by randomly clicking the pages, but imagine what happens when a doc gets even a bit bigger.

**Comment by kirsan31** [comment]
> If you'd prefer to turn off the code analyzer completely, it can be done in the [General settings](https://ewsoftware.github.io/VSSpellChecker/html/b4a8726f-5bee-48a4-81a9-00b1be332607.htm) by setting the "Enable spell checking code analyzer in supported languages" option to No.

Thanks God we have this options 🫡 IMHO it's must be set by default to `NO`...

**Comment by Doomic** [comment]
it took me a while to figure this one out.. thanks for sharing the solution. And I agree; default "no" would have been better.

**Comment by dirtygooback** [comment]
@EWSoftware - Perhaps adding a supression to the global configuration would be a solution. I don't want things like Api to ever be caught by the checker and I don't want unneeded config files, .xml or .cs, littering my projects.
