### ISSUE TITLE
Validate only comments

### ISSUE THREAD

**Issue by digocesar** [EWSoftware/VSSpellChecker#294]
How can I configure Spell Checker to validate strings only in comments and regions?
I don't want to validate class name, fields and others...

**Comment by EWSoftware** [comment]
You can turn off the code analyzer in the general settings.

**Comment by EWSoftware** [comment]
I don't use Resharper but I know it uses NHunSpell as well and depending on which extension gets loaded first determines which one's dictionary gets used.  This was discovered recently in fixing a long-standing issue with the Visual Studio text box spell checking option in my extension not working properly.  That may be why you're seeing the change in behavior.

In general, they probably shouldn't be used together for spell checking editors since it's a duplication of functionality.  Resharper is also more invasive as far the smart tags go so it tends to override the ones from my extension in the editor.  They're still there just not accessible.  People that do use them both typically only use mine for spell checking the Visual Studio text boxes and solution/project spell checking leaving Resharper to handle the editor.

**Comment by digocesar** [comment]
My project has comments in Portuguese and code in English. So I use VSSpellChecker for commments and ReSharper for code.
I install ReSharper and disable typo in comments. But it disables the VSSpellChecker too. And if disabling ReSpeller feature, it completely disables the VSSpellChecker too.
I had tested invert install order. But no luck.

**Comment by digocesar** [comment]
ReSharper has this registered issue:
[RSRP-472628](https://youtrack.jetbrains.com/issue/RSRP-472628) ReSharper suppresses Visual Studio Spell Checker add-on often

Unchecking the option has solved my problem. But I don't know if it has other collateral problems.
![image](https://github.com/EWSoftware/VSSpellChecker/assets/17618149/6d694579-c81e-4b94-9ba3-c9946517545b)
