### ISSUE TITLE
Simple queation. How to use VSSpellChecker.editorconfig to check only *.vb files

### ISSUE THREAD

**Issue by aaaron99** [EWSoftware/VSSpellChecker#301]
Need documation for how to use VSSpellChecker.editorconfig to check only the *.vb files

Also, how to edit previous "ignore all" selections

**Comment by EWSoftware** [comment]
Edit the global or solution/project configuration and disable the [spell checker options](https://ewsoftware.github.io/VSSpellChecker/html/b4a8726f-5bee-48a4-81a9-00b1be332607.htm) in the [*] section that covers all files.  Enable the spell checker in the [*.vb] section so that it only spell checked *.vb files.  If you have [ignored words](https://ewsoftware.github.io/VSSpellChecker/html/c592c4d8-7387-47fe-9b79-28bf0168f447.htm), they're likely already in the configuration.  If not, you can add them back in.
