### ISSUE TITLE
Still flags misspelled words in // comments even though it it disabled

### ISSUE THREAD

**Issue by ra-dave** [EWSoftware/VSSpellChecker#310]
I've just started using this and even though I've disabled checking // comments (as well as all other comments), when I run spell check it continues to flag misspellings in comments.  Why?

**Comment by EWSoftware** [comment]
Are you using Visual Studio 2022?  If so, did you disable the [built-in spell checker](https://ewsoftware.github.io/VSSpellChecker/html/e339cac1-9783-4c2a-919f-88436c78fef8.htm)?  It's likely you're seeing its flags rather than mine.  Other extensions such as Resharper and GhostDoc also include spell checkers so if using them, you'd need to disable their spell checking options as well.
