### ISSUE TITLE
"Add to Dictionary" should add to the most local settings file

### ISSUE THREAD

**Issue by breyed** [EWSoftware/VSSpellChecker#41]
When I click "Add to Dictionary" on a word, the word gets added to dictionary next to the Global Spell Checker Configuration, even if I have a solution-level configuration defined. It would be better to add to a solution-level dictionary so that it can be checked into source control.

On the topic of adding to source control, it would be good if the configuration file were kept sorted. That would minimize the number of merge conflicts on a team. Adding to the end happens to be the worst place, since any concurrent changes always end up being merges.

As a point of comparison, Android Studio's standard project structure includes user dictionaries intended for check-in, although it uses a naming convention so that each developer gets his own dictionary.

**Comment by EWSoftware** [comment]
User dictionaries are associated with the dictionary, not any particular configuration file.  User dictionaries for global dictionaries are stored in the global configuration location.

If you add the dictionary to the solution or project and use a solution or project configuration file to specify the dictionary's location, it will override the global dictionary.  Any words added to the user dictionary will then be stored with the solution/project dictionary and can be checked into source control along with the dictionary being used.

As currently written, it just appends the word to the end of the file rather than rewriting the entire list.  However, it can be updated to sort and write the entire list to the file.

**Comment by breyed** [comment]
I can't get this to work for me. I added `en-US_User.dic` to the Solution Items. The file is in the solution root folder. None of the words in that dictionary are known to the spell checker. When I click to add a word to the dictionary, it still goes in the global dictionary.

I tried with and without a .vsspell config file and tried adding `.` as a dictionary folder. It didn't matter. Is there a specific name or the like that the dictionary should have?

**Comment by EWSoftware** [comment]
You need to add the dictionary as well.

**Comment by breyed** [comment]
I already added the user dictionary with the non-standard words. Do you mean the 50,000 word English dictionary? That would be disappointing to have to add to each solution.

**Comment by EWSoftware** [comment]
Yes, I mean the .aff and .dic files (en_us.aff and en_us.dic for example).  Dictionaries are global resources.  Once loaded, they are used for all files within the solution.  It also guarantees you're all using the same dictionary.

**Comment by breyed** [comment]
I'd suggest allowing for just a user dictionary without a copy of the master dictionary. The downside as you mention is that the master dictionary could vary. However, realistically, users will pretty much stay on the latest version of the spell checker extension, and if someone is out of date by a bit, it's not a big deal. I believe the downside is outweighed by the upsides of inheriting the extension dictionary, specifically inheriting its improvements over time (vs being stuck with your forked version), and one less file in your project.

**Comment by EWSoftware** [comment]
I'll see what I can do.
