### ISSUE TITLE
Global configuration not loading correctly

### ISSUE THREAD

**Issue by Magnificus36** [EWSoftware/VSSpellChecker#47]
I've just updated to the latest version (in VS2013) and now the global default dictionary is en-US instead of en-GB.
My VSSpellChecker.vsspell is unchanged.

**Comment by EWSoftware** [comment]
The default language element changed in the latest release.  It may not be picking it up when trying to convert it.  Have you edited the configuration and explicitly added en-GB as the selected language?

**Comment by Magnificus36** [comment]
Now I had some more time to look at it I found what was the problem.
I had to click 'Add'... xD
Did not really look below the dropdownmenu, not noticing that the empty listbox and those buttons where in the same groupbox as the dropdownmenu.

It would have been nice if the language I had selected in the previous version would have been added automatically. And I might have noticed those other UI elements if the listbox was not empty at the beginning.

**Comment by EWSoftware** [comment]
I may have been picking it up for use in spell checking files prior to editing the configuration.  It may not be picking it up and adding it as a default when editing the global configuration.

**Comment by Magnificus36** [comment]
The reason I noticed the change was because my documents where spell checked with en-US after de update.

**Comment by DaveRobSwEng** [comment]
I was confused too - VS2015 was using en-US but VS2013 appeared to be using en-GB. Checking the global config file C:\Users\robinsond\AppData\Local\EWSoftware\Visual Studio Spell Checker\VSSpellChecker.vsspell I could see:
<SpellCheckerConfiguration Format="2015.7.24.0">
  <DefaultLanguage>en-GB</DefaultLanguage>

The Selected Language element was only added after using the 'Add' button:
  <SelectedLanguages>
    <LanguageName>en-GB</LanguageName>
  </SelectedLanguages>

This is required to get VS2015 using the correct language.

I think the UI may be improved by showing the available languages drop-down only when the user clicks 'Add' because that makes it clearer (to me anyway) what I have to do to add a language. If no selected language is present then the list box could hold a dummy item: 'Please add a selected language'

**Comment by EWSoftware** [comment]
Odd if it worked in VS2013 but not VS2015 since they use the same code and configuration file.  It did work initially when I was making the changes but it could be something I changed prevents it from picking up the old setting now.  Anyway, I will add an indicator to note that a language needs to be added if one isn't there when the global configuration is edited.
