### ISSUE TITLE
Double clicking a source code file with a .vsspell file causes it to expand

### ISSUE THREAD

**Issue by TheLordOfTheVoid** [EWSoftware/VSSpellChecker#48]
Normally when you double click a source file in the solution explorer it opens the file, but does not expand the its contents (like classes and global variables). However when that file has an associated .vsspell file, it expands it. This feels awkward. I have experienced this in vs2015 community and in vs2013 professional.

**Comment by EWSoftware** [comment]
I'm not able to duplicate this behavior.  What type of files are you seeing this happen on?  If I add a configuration file to a C# source code file and then double click on either the icon or the name in Solution Explorer, it opens the source code file.  The collapsed or expanded state of the related node doesn't change.

**Comment by TheLordOfTheVoid** [comment]
I'm using c++ header and source files (.h and .cpp)

**Comment by EWSoftware** [comment]
This seems to be a quirk of the C++ project system.  Perhaps it's because C++ projects group by folder rather than by file.  It does the same thing in a C++ CLR project if you add a Windows form or user control class.  The .resx file is nested and opening the form designer expands the file node to show the .resx file.

**Comment by TheLordOfTheVoid** [comment]
Ok, thanks anyway.
