### ISSUE TITLE
Words are not identified correctly in strings that have the @ symbol to allow verbatim text.

### ISSUE THREAD

**Issue by t-johnson** [EWSoftware/VSSpellChecker#60]
the tool will incorrectly tell me that "emp" is not a word in the following example:

string test = @"c:\temp\";

expect that the tool correctly identifies words when the string is prefixed with the @ symbol

**Comment by EWSoftware** [comment]
I can probably update the solution/project spell checking tool window to ignore such cases.  However, with spell check as you type, I'm pretty sure there just isn't enough context at the point the word splitting occurs to know what the span is in.  If you never want to spell check verbatim strings, you can turn off that option in the C# category in the configuration settings.

**Comment by dilijev** [comment]
It seems an easy fix would be to store the location of each word at line number, column, and then the only problem would be if the number of lines was changed or if there were multiple spell-check problems on the same line. That's much easier to deal with when trying to fix hundreds of misspellings in a large file.

**Comment by EWSoftware** [comment]
I think you may have replied to the wrong issue.  Regardless, the problem is that column varies by settings based on whether you are using tabs or spaces and, if tabs, how many spaces per tab.  Tab size can vary by file type.  There's no reliable way to tell what the actual column is.  That's why everything is stored by offset.  As I said in the other issue, deal with the issues through the tool window first.  If there are multiple issues on a line, you'll still get to them through the tool window.  If you want to make other edits, wait until you're done with the spell checking issues.
