### ISSUE TITLE
Can html attributes be ignored?

### ISSUE THREAD

**Issue by rickmccabe2** [EWSoftware/VSSpellChecker#61]
VS2013 Professional

I've just installed this and it looks to be fantastic but all my css classes in MVC html attributes are being flagged as spelling errors.

e.g. 
@Html.Label("test", new { @class = "col-md-3 control-label" })
md is being flagged as a spelling mistake,

Is this expected behaviour? Can I turn this off? 

Thanks,

**Comment by EWSoftware** [comment]
Yes, that is expected behavior.  The spell checker doesn't know what type of string it is just that it is a string containing potential words.  You can use the [Exclusion Expressions](https://github.com/EWSoftware/VSSpellChecker/wiki/6216eedb-6434-4cad-be06-576814e0b735) configuration category to define regular expression matches that can exclude such ranges from being spell checked.
