### ISSUE TITLE
Need option for ignoring function names.

### ISSUE THREAD

**Issue by Durimar** [EWSoftware/VSSpellChecker#64]
Is it posible to add some option (or two different options) to ignore function names in comments?

C code:
----------
        int myvariable;

        // 1. Call myfunction() by pointer from DLL.
        p();

        // 2. Call mysuperfunction() first time to do something.
        mysuperfunction();

        // 3. Call mysuperfunction second time to do something.
        mysuperfunction();

        // 4. Initialize myvariable. 
        myvariable = 0;
---------

1. Ignore 'myfunction' in comment - because it looks like function name. 
2. Ignore 'mysuperfunction' in comment - there is real function with 'mysuperfunction' name somewhere in project/solution and in second case - because it looks like function name.
3. Ignore 'mysuperfunction' word in comment because there is real function with 'mysuperfunction' name somewhere in project/solution.
4. Ignore 'myvariable' word in comment because there is real local variable with 'myvariable' name.

It can be two options:
1. Ignore word if it looks like function signature.
2. Ignore word if there is existing function/variable/type with this name.

Thanks.

**Comment by franzalex** [comment]
If it is possible, try naming your functions with the PascalCase or camelCase. VS Spell Checker ignores words that are in Pascal Case or camelCase.

**Comment by EWSoftware** [comment]
For #1, the problem is that you know it's a function name but the spell checking code doesn't.  It's just an arbitrary string of lowercase letters that isn't in the dictionary.  The assumption that if it's followed by parentheses it's a function may hold in some cases but what if there is text between them?  Are they example parameters or parameter types/names or did someone forget to put a space between a word and the parentheses?  The spell checker does do something similar for filenames and e-mail addresses but those cases are much more prevalent and it omits more false reports than actual misspellings.  As noted by @franzalex, Pascal or camel case names are ignored by default.  I know you can't rewrite an entire code base for that but I'm not sure there's much benefit in trying to handle these cases since Pascal and camel case are typical in most projects.

For the rest, parsing the code just isn't possible to find all known variables and functions names regardless of scope within the solution and any referenced assemblies/libraries.  The spell checker just gets spans of text.  It doesn't know anything about the given language or the syntax of the file its running against other than what it can get from the filename extension and content type.

If the names occur often enough, you can add them as ignored words in a project-specific configuration file.  Likewise, if they follow a common pattern, you can exclude ranges of text by regular expression using the Exclusion Expressions configuration category.

**Comment by Durimar** [comment]
Thanks for answer :)

For 1. I just talked about trying to detect function signature. 
For example:
// myfunc - this is not function
// myfunc() - this is function - ONLY if option enabled.
// myfunc(s) - this is function - ONLY if option enabled.
// myfunc(s,s) - this is function - ONLY if option enabled.

Yes. This can make false reports. This must be disabled by default. But if i want this... and if i understand that i am doing - i can enable this feature.

For 2,3,4 - you can get all known variables and functions names from VisualStudio intellisense database for solution/project. VisualStudio Extention can acces to it. 
I am not sure, but i think that IntelliSense Visual Studio the extensibility APIs is somewhere under the Microsoft.VisualStudio.Languages.IntelliSense namespace.

Sorry for my poor english. :)
