### ISSUE TITLE
Add ability to ignore everything between tags

### ISSUE THREAD

**Issue by PhatWrat** [EWSoftware/VSSpellChecker#65]
Feature request.

I have told VSSpellChecker to "ignore once" a group of words that are "misspelled".  This works fine until I close VS and come back the next day.  When the solution is re-opened, VSSpellChecker seems to have forgotten that I said to ignore those words.  Rather than (just) trying to fix this bug, I suggest adding the ability to ignore blocks of code by adding comments similar to how ReSharper does it.  
(example:
// ReSharper disable InconsistentNaming
... 
multiple lines of code
 ...
// ReSharper restore InconsistentNaming

OR

// ReSharper disable once InconsistentNaming
single line of code
)

I tried using the "Exclusion Expressions" feature, but couldn't get it to work (I'm probably doing something wrong.  The RegEx I used was \/\/spellcheck disable[ -~\s]*\/\/spellcheck restore).  Again, similar to how ReSharper does it, it would be nice if I could just choose "Disable and restore with comments" from the context menu when I have a spelling error and then just move the comments that were auto-generated to wherever makes the most sense.

Disable and restore would be a useful feature since, in my experience, things that are intentionally misspelled are often grouped tightly together.  The single-line ignore is probably too verbose for a spelling error and simply remembering "ignore once" commands would be much better.

**Comment by EWSoftware** [comment]
Words ignored through the smart tag or tool window buttons are only ignored for the session.  If you want them ignored permanently, you do need to add them to the Ignored Words category in the global configuration or a solution, project, or file configuration.  See the help topics in the wiki for more information.

The exclusion expression `// spellcheck disable.*?// spellcheck restore` will work in some cases for solution/project spell checking if you enable the Ignore Case and Single Line options.  However, currently it only works if there are no other span types within the range.  For example, if there are XML comments elements within it, they are further broken down into individual spans so it wouldn't work in that case.  As long as the range is one contiguous span, it would be ignored.

It won't work for Spell Check as You Type due to the way the spell checker is called for changed spans.  If you make a change to a line, that's all the spell checker will typically see.  It won't necessarily see any of the surrounding lines for context to know if it should spell check the text or not.  It would need to know the existing ignored ranges up front, track them as they changed, as well as know when ignored ranges were added and removed.  I'm not sure there's a good way of doing that and still let it work with any file type.  As such, I doubt this is something I will add.

**Comment by EWSoftware** [comment]
See issue #166.  I've implemented support for that which is similar and it will be in the next release.  I can't support ranges or "just once" though as that would get too complicated.
