### ISSUE TITLE
Add All Words

### ISSUE THREAD

**Issue by KDHERaymond** [EWSoftware/VSSpellChecker#70]
Ran into a .tdf while spellchecking my site.  Got around 5000 "Mispelled Words".  All of these words are spelled correctly and an "Add All Words" button would simplify this situation greatly.

**Comment by EWSoftware** [comment]
I'm not sure there's any benefit to bulk adding 5000 words to the dictionary, especially if it's used by accident.  I don't know what a .tdf file is but if it's not something you'd normally want spell checked, I'd suggest adding it as an excluded file extension.

**Comment by KDHERaymond** [comment]
The file seems to be a German dictionary, and is a situation where a bulk add would be useful, unless there are files we can download and import to the spell checker to add other languages, simply opening a file with the language you wish to add and hitting add all would be the easiest way to import them.

And as for accidents, a simple "Are you sure you want to add all words to dictionary" prompt would give the user ample warning to avoid an accident.  This is just something I ran into.

**Comment by EWSoftware** [comment]
You can add dictionaries for other languages and add folder/file specific configurations to check folders/files against a specific dictionary.  The package comes with dictionaries for several languages by default.  See the configuration topics in the wiki:

- [Configuration Options](https://github.com/EWSoftware/VSSpellChecker/wiki/fb81c214-0fe0-4d62-a172-d7928d5b91d5)
- [Configuration Files](https://github.com/EWSoftware/VSSpellChecker/wiki/7b2bc3bb-5b5c-4d17-a88e-d58b476e49ab)

Since it appears to be a dictionary already, it's probably not something worth spell checking anyway and may be a candidate for ignoring by extension.
