### ISSUE TITLE
hotkeys/shortcuts

### ISSUE THREAD

**Issue by etkid2015** [EWSoftware/VSSpellChecker#71]
Does VSSpellChecker already have hotkeys or shortcuts for ignore, ignoreAll, and "add to dictionary"?

**Comment by EWSoftware** [comment]
The buttons in the tool windows do have hot keys.  Holding down Alt while the tool window has the focus should show them if they aren't visible by default based on your system settings.  The menus items on the smart tags don't.  There are no global hot keys since there are not global commands to which they could be attached.

**Comment by michaelosthege** [comment]
What about Ctrl+. ?
Whenever I see something underlined, my first reaction these days is to press Ctrl+.

I even do this in Word and PowerPoint. It'd be so great to have that shortcut!

**Comment by EWSoftware** [comment]
Yes, Ctrl+. to show the smart tag actions is standard behavior so that's built in.

**Comment by michaelosthege** [comment]
Oh indeed it works. (if there's no conflicting quick action.)
