### ISSUE TITLE
Consider adding an option to spell check mixed case words

### ISSUE THREAD

**Issue by Tom-Jans** [EWSoftware/VSSpellChecker#74]
Just installed in visual studio 2015. Unfortunately it doesn't check the spelling of method names and region names. Can i enable this in settings?

**Comment by EWSoftware** [comment]
In source code, it'll only check comments and strings, not code outside of those constructs.  However, it should spell check the text after the `#region` keyword.  Can you give an example that doesn't?

**Comment by Tom-Jans** [comment]
#region TalentsAvailabel
       #region SkillsAailable

These two didn't show as incorrect.

**Comment by EWSoftware** [comment]
It's because they are mixed case.  It doesn't spell check words in mixed case since they typically aren't real words.  To do it properly, you'd have to split the "word" on the uppercase letters and present each as a separate word.  That would catch those in your example but also could generate a lot of false reports.  It's an option I considered in the past but it was never requested so never implemented it.

**Comment by Tom-Jans** [comment]
I understand is it would be nice if you could implement it. Perhaps as a setting so that if it generates to much false reports for people they can disable it. Or just leave it disabled by default. If i have the time i could try and implement it myself and send a pull request. But i'm currently a bit too occupied to check your code and search for where to implement it.

**Comment by EWSoftware** [comment]
I turned out to be relatively simple to implement.  I've added an "Ignore words in mixed case" option for the next release.  It can be turned off to spell check mixed/camel case words.

**Comment by Tom-Jans** [comment]
Thanks it works as a charm.
