### ISSUE TITLE
PHP files not checked

### ISSUE THREAD

**Issue by FireEmerald** [EWSoftware/VSSpellChecker#80]
Got a project with many **\*.php** files and noticed, that the **VSSpellChecker** doesn't work at all with these files. Is this intended? (no support for *.php files?)

**Comment by EWSoftware** [comment]
Visual Studio doesn't support PHP out of the box so it's just opening them as normal text files.  The solution/project spell check is treating them as HTML files for lack of something better since the few examples I've got are more HTML than anything else.  Chances are it's not finding much to spell check using that definition.

I can't create a tagger for use in the Visual Studio editor since I don't know what content types and classification names might be used by anybody that's created third-party support for PHP.  They'd have to [do that](https://github.com/EWSoftware/VSSpellChecker/wiki/df2a45c1-1996-46f6-9d33-e73f0fa1d88a).

For solution/project spell checking support, if you can come up with a better set of definitions to identify the parts of a PHP file that needs spell checking, you can create a classification configuration file to override the default support.  See the [Defining Solution/Project Spell Check Classifiers](https://github.com/EWSoftware/VSSpellChecker/wiki/0ff35371-69b5-48dd-a062-037abe2469de) topic for more information on that.

**Comment by FireEmerald** [comment]
Seems like the spell checker ignores completely all php elements, as written here:
- https://github.com/EWSoftware/VSSpellChecker/blob/82d9339bad13fff9243225e70f7cd898968e9aac/Source/VSSpellChecker/ProjectSpellCheck/HtmlClassifier.cs#L114

Indeed VS doesn't support php files by default, but i'm using [*PHP Tools for Visual Studio*](https://visualstudiogallery.msdn.microsoft.com/6eb51f05-ef01-4513-ac83-4c5f50c95fb5).

**Comment by EWSoftware** [comment]
I don't know anything about PHP so parsing it isn't something I can do.  Overriding the classification configuration using the Regex classifier may allow it to be done without writing code.

As noted, I can't do the tagger for the editor.  The company that does the PHP extension would need to do that.

**Comment by FireEmerald** [comment]
Ok, for me it would be enough if the spell checker would interpret php files as plain text, so changed the Classifier for php files as shown below:
```xml
<Classifications>
  <!-- A simple example that maps new file types to existing classifier definitions -->
  <Extensions>
    <Extension Value="php" Classifier="PlainText" />
  </Extensions>
</Classifications>
```
But it won't work. (C:\Users\<user>\AppData\Local\EWSoftware\Visual Studio Spell Checker\Classifications.config)

**Comment by EWSoftware** [comment]
Are you using the latest release?  When I add the above configuration it works for me and spell checks the one's I've got as plain text.  The configuration is only for solution/project spell checking.  They're treated as plain text by default in the editor.  If it's not doing it in the editor, I suppose it's possible that the editor is perhaps treating it as XML rather than plain text if it looks enough like XML.

**Comment by FireEmerald** [comment]
Shouldn't it impossible that the editor is treating it as XML, if i override the Classifier **explicit** with PlainText?
- Example: New c# project with a file called test.php, the spell checking won't work - and there are only five rows, so it can't look like XML:

![2016-04-10 00_17_02-delete - microsoft visual studio](https://cloud.githubusercontent.com/assets/1107939/14406748/b9be19c2-feb1-11e5-9000-d3a969737626.png)

**Comment by EWSoftware** [comment]
It was just speculation.  Remember that you've got the PHP tools installed, I don't.  For you, it's probably defaulting to the generic code comment tagger since the tools are providing language support so if it finds anything it's because the span classifications match some of the common ones.  Unless the provider of the PHP tools creates a tagger that handles the classification span names that they are using, you won't get proper support in the editor.

**Comment by jakubmisek** [comment]
In case of PHP Tools, the PHP buffer is created as a projection within HTML/HTMLX buffer.

Classification names within the projected buffer are of standard comment, text, string types.

**Comment by FireEmerald** [comment]
So there won't be any fix/implementation?

**Comment by EWSoftware** [comment]
See my replies above, this isn't something I can do in the editor and I don't know PHP well enough to create the classification definition for solution/project spell checking.

**Comment by Miloslav** [comment]
We (Creators of PHP Tools) will take a look if we could do the tagger part. We'd love to have this working.

**Comment by Miloslav** [comment]
I've checked the VsSpellChecker code and it seems we shouldn't need to create any special tagger as PHP classifier returns ClassificationSpans that are handled in CommentTextTagger. 

The problem is that CommentTextTagger is not created for our buffer. It all comes down to this file:
SpellingServiceFactory.cs:91 where our text buffer gets disabled, because it's secondary buffer and buffer.GetFilename returns null. Therefore result of GetConfiguration is null, if we would return the configuration, php code would get correctly spellchecked. 

This also happens for C#/VB in razor files or aspx files, no problem for css or js though...

**Comment by FireEmerald** [comment]
@Miloslav So you will update PHP Tools to return the configuration? Would be nice if you could give a short reply, when it's fixed.

**Comment by Miloslav** [comment]
@FireEmerald Please update to the latest VSSpellchecker, it will work with currently opened php document. For project-wide spell checking we will have to find a way to provide VsSpellChecker with classifications from the whole project/solution, doing it with regexp is not really efficient or maintainable.
