### ISSUE TITLE
Support Visual Studio 15

### ISSUE THREAD

**Issue by d-kr** [EWSoftware/VSSpellChecker#82]
Even though Visual Studio 15 (nor 2015; that thing that was presented at /build/) is in the preview stage can SpellChecker support it already?

**Comment by EWSoftware** [comment]
Getting it to install is just a matter of updating the maximum version supported in the VSIX manifest.  Whether it works without issue will need some testing.  I'll take a look at it when I get some time but I don't have an estimate on when that will be.

**Comment by EWSoftware** [comment]
The extension appears to work okay in the full install of VS 15 Preview 2.  However, the installer doesn't detect a usable version if you install the new lightweight version.  I don't think that version's complete yet so that may be why.  Support for the full version of the 15 preview will be in the next release (no time line just yet).
