### ISSUE TITLE
"localhost" spell checking proposals

### ISSUE THREAD

**Issue by liebharc** [EWSoftware/VSSpellChecker#88]
Hello,

So first thanks for providing this really useful VS add-on. I was today quite speechless as I saw the proposed corrections for the word "localhost" with the en-US dictionary:

- "local host"
- "local-host"
- "holocaust"
- "Holocaust"

It's quite common that spell checking gets the semantics wrong and as I can see the add-on uses a standard dictionary. But I wonder if you still want to add "localhost" to the default dictionary since it's a fixed term in IT (`ping localhost`) and Holocaust is a really terrible proposal.

Best regards
Christian

**Comment by EWSoftware** [comment]
The dictionaries are standard Open Office dictionaries I obtained from the Open Office extensions site referenced in [the wiki](https://github.com/EWSoftware/VSSpellChecker/wiki/508e7e8f-e00f-43f1-ad4c-5439ddec84b8).  There are many IT terms that they don't contain so they just need to be added to the user dictionary as you find them.

Since I supply dictionaries for various common languages and I didn't create any of them, I don't want to take on the task of maintaining the dictionaries by adding words that everybody feels should be there.  That's something that should be taken up with the creators of the dictionaries to see if they care to add the terms to the official copies that they maintain.

**Comment by liebharc** [comment]
Thanks for the quick response. I understand your reasoning and will try to get the update into the OO dictionaries - given that I find the right defect tracker for it.
