### ISSUE TITLE
Incorrect detection using anonymous Actions

### ISSUE THREAD

**Issue by dt-fastec** [EWSoftware/VSSpellChecker#89]
Hi,

if you use are using an anonymous Action, the Spell Checker indicates key words like foreach as an incorrect speling.
For example:

![spellcheckerbug](https://cloud.githubusercontent.com/assets/5908198/15857550/41a6eed0-2cbc-11e6-8c6f-f30bba59f8e1.png)

**Comment by dt-fastec** [comment]
Mmh, it does not seem to be a problem forced by the Action only. I can't reproduce it in separate file. It must be a more complex situation that forces the incorrect spelling detection.

**Comment by EWSoftware** [comment]
This does happen occasionally though I haven't been able to pin the cause down.  Typically it happens when cutting and pasting code or uncommenting previously commented code.  The internal state that tracks the spell checkable ranges gets out of synch.  Making an edit on one of the affected lines gets it back in synch.
